name: fortune
description: A dart library for retrieving fortunes.
version: 0.1.0
author: 'rinukkusu <rinukkusu@auen.land>'
homepage: https://github.com/rinukkusu/fortune-dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: '^1.3.0'
