name: fortune
description: A dart library for retrieving fortunes.
version: 0.0.1
author: 'rinukkusu <rinukkusu@auen.land>'
homepage: https://github.com/rinukkusu/fortune-dart

environment:
  sdk: '>=1.23.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
